export const INTEGRATIONS = {
  SHOPIFY: {
    id: "shopify",
    name: "Shopify",
    description:
      "Connect your Shopify store to sync orders, products, and customers",
    icon: "logos:shopify",
    color: "#7AB55C",
    category: "ecommerce",
    required: true,
    features: [
      "Real-time order sync",
      "Product inventory tracking",
      "Customer data sync",
      "Refund tracking",
    ],
  },
  META: {
    id: "meta",
    name: "Meta Ads",
    description: "Track your Facebook and Instagram advertising performance",
    icon: "grommet-icons:meta",
    color: "#0668E1",
    category: "marketing",
    required: false,
    features: [
      "Campaign performance",
      "Ad spend tracking",
      "ROAS calculation",
      "Audience insights",
    ],
  },
  GOOGLE: {
    id: "google",
    name: "Google Ads",
    description: "Monitor your Google Ads campaigns and performance metrics",
    icon: "logos:google-ads",
    color: "#4285F4",
    category: "marketing",
    required: false,
    comingSoon: true,
    releaseDate: "Coming soon",
    features: [
      "Campaign analytics",
      "Keyword performance tracking",
      "Conversion attribution",
      "Cost and budget optimization",
    ],
  },
};
