export const SHOPIFY_WEBHOOK_TOPICS = [
  "app/uninstalled",
  // Billing
  "app_subscriptions/update",
  // The following billing topics are included for completeness; some may
  // not be registrable via GraphQL in all API versions but we handle them
  // if Shopify delivers them to our endpoint.
  "app_subscriptions/cancelled",
  "app_subscriptions/approaching_capped_amount",
  "app_subscription_billing_attempts/success",
  "app_subscription_billing_attempts/failure",
  "app_purchases/one_time",
  // Shop and collections
  "shop/update",
  "collections/create",
  "collections/update",
  "collections/delete",
  "orders/create",
  "orders/paid",
  "orders/cancelled",
  "orders/fulfilled",
  "orders/partially_fulfilled",
  "orders/edited",
  "orders/delete",
  "products/create",
  "products/update",
  "products/delete",
  "refunds/create",
  "customers/create",
  "customers/update",
  "customers/delete",
  "customers/enable",
  "customers/disable",
  "inventory_levels/update",
  "inventory_items/create",
  "inventory_items/update",
  "inventory_items/delete",
  "order_transactions/create",
  "fulfillments/create",
];
